# Generated by Django 3.0.2 on 2020-01-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyracoes_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='ration',
            name='ration_port',
        ),
        migrations.AddField(
            model_name='ration',
            name='ration_type',
            field=models.ManyToManyField(to='pyracoes_main.Type'),
        ),
        migrations.RemoveField(
            model_name='animal',
            name='animal_age',
        ),
        migrations.RemoveField(
            model_name='ration',
            name='ration_age',
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_age',
            field=models.ManyToManyField(to='pyracoes_main.Age'),
        ),
        migrations.AddField(
            model_name='ration',
            name='ration_age',
            field=models.ManyToManyField(to='pyracoes_main.Age'),
        ),
    ]
