# Generated by Django 3.0 on 2020-01-15 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyracoes_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='ration',
            name='ration_weight',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_password',
        ),
        migrations.AddField(
            model_name='ration',
            name='ration_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ration',
            name='ration_type',
            field=models.ManyToManyField(to='pyracoes_main.Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_django',
            field=models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='animal',
            name='animal_age',
        ),
        migrations.RemoveField(
            model_name='ration',
            name='ration_age',
        ),
        migrations.RemoveField(
            model_name='ration',
            name='ration_port',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_animals',
            field=models.ManyToManyField(blank=True, to='pyracoes_main.Animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_port',
            field=models.ManyToManyField(to='pyracoes_main.Port'),
        ),
        migrations.AddField(
            model_name='ration',
            name='ration_classification',
            field=models.ManyToManyField(to='pyracoes_main.Classification'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_age',
            field=models.ManyToManyField(to='pyracoes_main.Age'),
        ),
        migrations.AddField(
            model_name='ration',
            name='ration_age',
            field=models.ManyToManyField(to='pyracoes_main.Age'),
        ),
        migrations.AddField(
            model_name='ration',
            name='ration_port',
            field=models.ManyToManyField(to='pyracoes_main.Port'),
        ),
    ]
