# Generated by Django 3.0 on 2020-01-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyracoes_main', '0002_ration_ration_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_weight',
        ),
    ]
