# Generated by Django 3.0.2 on 2020-01-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyracoes_main', '0002_auto_20200102_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_port',
            field=models.ManyToManyField(to='pyracoes_main.Port'),
        ),
        migrations.AddField(
            model_name='ration',
            name='ration_port',
            field=models.ManyToManyField(to='pyracoes_main.Port'),
        ),
    ]
