# Generated by Django 3.0.2 on 2020-01-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyracoes_main', '0005_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ration',
            name='ration_classification',
            field=models.ManyToManyField(to='pyracoes_main.Classification'),
        ),
    ]
