# Generated by Django 3.0.2 on 2020-01-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyracoes_main', '0009_remove_ration_ration_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ration',
            name='ration_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
