# Generated by Django 3.0 on 2020-01-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyracoes_main', '0002_auto_20200115_1949'),
        ('pyracoes_main', '0013_auto_20200112_1852'),
    ]

    operations = [
    ]
